//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Charge
    {
        public int ChargeID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> units { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> ReservationID { get; set; }
    
        public virtual Reservationz Reservationz { get; set; }
        public virtual Service Service { get; set; }
    }
}
