//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservationz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservationz()
        {
            this.Charge = new HashSet<Charge>();
        }
    
        public int ReservationID { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public Nullable<decimal> CustomizedPrice { get; set; }
        public string status { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> InvoiceNumber { get; set; }
        public Nullable<int> RoomNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Charge> Charge { get; set; }
        public virtual Customerz Customerz { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual Room Room { get; set; }
    }
}
